import Head from 'next/head'
import styles from './index.module.scss'
import React, { useEffect } from 'react';
import https from 'https';
import axios from 'axios';
import Link from 'next/link';

export default function Home({ cities }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='row g-4'>
        {cities?.map((item) => (
          <div className='col-md-6 col-lg-4 col-12'>
            <Link href={{
              pathname: "/[slug]",
              query: { slug: item.seoUrl }
            }}>
              <a title={item.cityName} className={`shadow p-4 h-100 ${styles.city}`}>
                {item.cityName}
              </a>
            </Link>

          </div>
        ))}
      </div>
    </>
  )
}

export const getStaticProps = async () => {
  const agent = new https.Agent({
    rejectUnauthorized: false
  });
  const cities = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/Cities/GetCityList`, { httpsAgent: agent })
    .then(resp => {
      return resp.data.entities?.map(item => {
        return {
          seoUrl: item.seoUrl.split("/")[2],
          cityName: item.ilAdi
        }
      })
    })
    .catch(err => {
      console.log("Errors Are ", err);
    });


  return {
    props: {
      cities: cities
    }
  }
}


